name: ci

on: push 

jobs:
  
  windows-msvc:
    name: ✨ windows-msvc
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: configure 
        run: cmake .
      - name: build 
        run: cmake --build .
      - name: 🔨 run print
        run: ./a.out.exe
