name: ci

on: push 

jobs:
  
  centos:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v2
    - name: What OS is running
      run: uname -a
    - name: gcc version
      run: g++ --version
    - name: Build test
      run: g++ -std=c++11 test.cpp

  gcc:
    runs-on: ubuntu-latest
    container:
      image: gcc
    steps:  
    - uses: actions/checkout@v2
    - name: What OS is running
      run: uname -a
    - name: gcc version
      run: g++ --version
    - name: Build test
      run: g++ -std=c++11 test.cpp
