name: ci

on: push 

jobs:
  
  atest:
    runs-on: ubuntu-latest
    container:
      image: alpine
    steps:  
    - uses: actions/checkout@v2
    - name: What OS is running
      run: uname -a
    - name: Build test
      run: cmake . 
